var phone_country_number_list = [
["アフガニスタン","93","Afghanistan"],
["アルバニア","355","Albania"],
["アルジェリア","213","Algeria"],
["アメリカンサモア","1","American Samoa"],
["アンドラ","376","Andorra"],
["アンゴラ","244","Angola"],
["アンギラ","1","Anguilla"],
["アンティグアバーブーダ","1","Antigua & Barbuda"],
["アルゼンティン","54","Argentina"],
["アルメニア","374","Armenia"],
["アルバ","297","Aruba"],
["アッセンション","247","Ascension Island"],
["オーストラリア","61","Australia"],
["オーストリア","43","Austria"],
["アゼルバイジャン","994","Azerbaijan"],
["バハマ","1","Bahamas"],
["バハレーン","973","Bahrain"],
["バングラディッシュ","880","Bangladesh"],
["バルバドス","1","Barbados"],
["ベラルーシ","375","Belarus"],
["ベルギー","32","Belgium"],
["ベリーズ","501","Belize"],
["ベナン","229","Benin"],
["バミューダ","1","Bermuda"],
["ブータン","975","Bhutan"],
["ボリヴィア","591","Bolivia"],
["ボスニアヘルツェゴヴィナ","387","Bosnia-Herzegovina"],
["ボツワナ","267","Botswana"],
["ブラジル","55","Brazil"],
["バージン諸島（英領）","1","British Virgin Islands"],
["ブルネイ","673","Brunei"],
["ブルガリア","359","Bulgaria"],
["ブルキナファソ","226","Burkina Faso"],
["ブルンジ","257","Burundi"],
["カンボジア","855","Cambodia"],
["カメルーン","237","Cameroon"],
["カナダ","1","Canada"],
["カボヴェルテ","238","Cape Verde Islands"],
["ケイマン諸島","1","Cayman Islands"],
["中央アフリカ共和国","236","Central African Republic"],
["チャド","235","Chad"],
["チリ","56","Chile"],
["中国","86","China"],
["クリスマス島","61","Christmas Island"],
["ココス諸島","61","Cocos Keeling Islands"],
["コロンビア","57","Colombia"],
["コモロ","269","Comoros"],
["コンゴ","242","Congo"],
["コンゴー民主共和国（旧ザイール）","243","Congo DPR (former Zaire)"],
["クック諸島","682","Cook Islands"],
["コスタリカ","506","Costa Rica"],
["クロアチア","385","Croatia"],
["キューバ","53","Cuba"],
["キプロス","357","Cyprus"],
["チェコ","420","Czech Republic"],
["デンマーク","45","Denmark"],
["ディエゴガルシア","246","Diego Garcia"],
["ジブティ","253","Djibouti"],
["ドミニカ","1","Dominica"],
["ドミニカ共和国","1","Dominican Republic"],
["東ティモール","670","East Timor"],
["エクアドル","593","Ecuador"],
["エジプト","20","Egypt"],
["エルサルヴァドル","503","El Salvador"],
["赤道ギニア","240","Equatorial Guinea"],
["エリトリア","291","Eritrea"],
["エストニア","372","Estonia"],
["エチオピア","251","Ethiopia"],
["フォークランド諸島","500","Falkland Islands (Malvinas)"],
["フェアロ諸島","298","Faroe Islands"],
["フィージー","679","Fiji Islands"],
["フィンランド","358","Finland"],
["フランス","33","France"],
["フランス領アンティル（グアドループ島）","590","French Antilles (Guadeloupe, St. Barthelemy, St. Martin)"],
["フランス領ギアナ","594","French Guiana"],
["フランス領ポリネシア","689","French Polynesia"],
["ガボン","241","Gabon"],
["ガンビア","220","Gambia"],
["グルジア","995","Georgia"],
["ドイツ","49","Germany"],
["ガーナ","233","Ghana"],
["ジブラルタル","350","Gibraltar"],
["ギリシャ","30","Greece"],
["グリーンランド","299","Greenland"],
["グレナダ","1","Grenada"],
["グアデルーペ","590","Guadeloupe"],
["グアム","1","Guam"],
["グアテマラ","502","Guatemala"],
["ギニア","224","Guinea"],
["ギニアビサオ","245","Guinea Bissau"],
["ガイアナ","592","Guyana"],
["ハイティ","509","Haiti"],
["ホンデュラス","504","Honduras"],
["香港","852","Hong Kong"],
["ハンガリー","36","Hungary"],
["アイスランド","354","Iceland"],
["インド","91","India"],
["インドネシア","62","Indonesia"],
["イラン","98","Iran"],
["イラク","964","Iraq"],
["アイルランド","353","Ireland"],
["イスラエル","972","Israel"],
["イタリア","39","Italy"],
["コートジボワール","225","Ivory Coast"],
["ジャマイカ","1","Jamaica"],
["日本","81","Japan"],
["ヨルダン","962","Jordan"],
["カザフスタン","7","Kazakhstan"],
["ケニア","254","Kenya"],
["キリバス","686","Kiribati"],
["北朝鮮","850","Korea, North"],
["韓国","82","Korea, South"],
["クウェイト","965","Kuwait"],
["キルギス","996","Kyrgyz Republic"],
["ラオス","856","Laos"],
["ラトヴィア","371","Latvia"],
["レバノン","961","Lebanon"],
["レソト","266","Lesotho"],
["リベリア","231","Liberia"],
["リビア","218","Libya"],
["リヒテンシュタイン","423","Liechtenstein"],
["リトアニア","370","Lithuania"],
["ルクセンブルグ","352","Luxembourg"],
["マカオ","853","Macao"],
["マケドニア","389","Macedonia"],
["マダガスカル","261","Madagascar"],
["マラウイ","265","Malawi"],
["マレーシア","60","Malaysia"],
["モルディブ","960","Maldives"],
["マリ","223","Mali"],
["マルタ","356","Malta"],
["マーシャル諸島","692","Marshall Islands"],
["マルチニーク島","596","Martinique"],
["モーリタニア","222","Mauritania"],
["モーリシャス","230","Mauritius"],
["マヨット","269","Mayotte"],
["メキシコ","52","Mexico"],
["ミクロネシア連邦","691","Micronesia"],
["モルドヴァ","373","Moldova"],
["モナコ","377","Monaco"],
["モンゴル","976","Mongolia"],
["モンテネグロ","382","Montenegro"],
["モントセルラット","1","Montserrat"],
["モロッコ","212","Morocco"],
["モザンビーク","258","Mozambique"],
["ミャンマー","95","Myanmar"],
["ナミビア","264","Namibia"],
["ナウル","674","Nauru"],
["ネパール","977","Nepal"],
["オランダ","31","Netherlands"],
["オランダ領アンティル","599","Netherlands Antilles"],
["ニューカレドニア","687","New Caledonia"],
["ニュージーランド","64","New Zealand"],
["ニカラグア","505","Nicaragua"],
["ニジェール","227","Niger"],
["ナイジェリア","234","Nigeria"],
["ニウェ","683","Niue Island"],
["ノーフォーク島","672","Norfolk Island"],
["北マリアナ諸島（サイパン、ロタ、ティニアン）","1","Northern Mariana Islands (Saipan, Rota, Tinian)"],
["ノルウェー","47","Norway"],
["オマーン","968","Oman"],
["パキスタン","92","Pakistan"],
["パラオ","680","Palau"],
["パレスチナ","970","Palestine"],
["パナマ","507","Panama"],
["パプアニューギニア","675","Papua New Guinea"],
["パラグアイ","595","Paraguay"],
["ペルー","51","Peru"],
["フィリピン","63","Philippines"],
["ポーランド","48","Poland"],
["ポルトガル","351","Portugal"],
["プエルトルコ","1","Puerto Rico"],
["カタル","974","Qatar"],
["レユニオン","262","Reunion Island"],
["ルーマニア","40","Romania"],
["ロシア","7","Russia"],
["ルワンダ","250","Rwanda"],
["サモア","685","Samoa"],
["サンマリノ","378","San Marino"],
["サントメプリンシペ","239","Sao Tome"],
["サウジアラビア","966","Saudi Arabia"],
["セネガル","221","Senegal"],
["セルビア","381","Serbia"],
["セイシェル","248","Seychelles"],
["シエラレオーネ","232","Sierra Leone"],
["シンガポール","65","Singapore"],
["スロヴァキア","421","Slovakia"],
["スロヴェニア","386","Slovenia"],
["ソロモン諸島","677","Solomon Islands"],
["ソマリア","252","Somalia"],
["南アフリカ","27","South Africa"],
["スペイン","34","Spain"],
["スリランカ","94","Sri Lanka"],
["セントヘレナ","290","St. Helena"],
["セントキットス（セントクリストファー）ネイビズ","1","St. Kitts (St. Christopher) & Nevis"],
["セントルシア","1","St. Lucia"],
["サンピエールミクロン島","508","St. Pierre & Miquelon"],
["セントヴィンセントおよびグレナディーン諸島","1","St. Vincent & Grenadines"],
["スーダン","249","Sudan"],
["スリナム","597","Suriname"],
["スワジランド","268","Swaziland"],
["スウェーデン","46","Sweden"],
["スイス","41","Switzerland"],
["シリア","963","Syria"],
["台湾","886","Taiwan"],
["タジキスタン","992","Tajikistan"],
["タンザニア","255","Tanzania"],
["タイ","66","Thailand"],
["トーゴー","228","Togo"],
["トケラウ諸島","690","Tokelau"],
["トンガ","676","Tonga"],
["トリニダッドトバゴ","1","Trinidad & Tobago"],
["トリスタンダクーニャ","290","Tristan da Cunha"],
["チュニジア","216","Tunisia"],
["トルコ","90","Turkey"],
["トルクメニスタン","993","Turkmenistan"],
["タークスカイコス諸島","1","Turks & Caicos Islands"],
["ツバル","688","Tuvalu"],
["ウガンダ","256","Uganda"],
["イギリス","44","UK"],
["ウクライナ","380","Ukraine"],
["アラブ首長国連邦","971","United Arab Emirates (UAE)"],
["アメリカ","1","United States (USA)"],
["ウルグアイ","598","Uruguay"],
["バージン諸島（米領）","1","US Virgin Islands"],
["ウズベキスタン","998","Uzbekistan"],
["バヌアツ","678","Vanuatu"],
["バチカン","39, 379","Vatican City"],
["ベネズエラ","58","Venezuela"],
["ベトナム","84","Vietnam"],
["ウェーク島","808","Wake Island"],
["ウオリスフチュナ","681","Wallis & Futuna"],
["イエメン","967","Yemen"],
["ザンビア","260","Zambia"],
["ジンバブエ","263","Zimbabwe"],
];
